package zadania;

import java.sql.*;

public class Cre1 {

    static public void main(String[] args) throws SQLException {
        new Cre1();
    }

    Statement stmt;

    Cre1() throws SQLException {
        Connection con = null;
        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");    //client
            con = DriverManager.getConnection("jdbc:derby://localhost/ksidb");    //connecting?
                                                                // 10.15.2.0:1527 wrong ip for sure - check
            stmt = con.createStatement();
            // łączenie z bazą i utworzenie obiektu typu Statement
        } catch (Exception exc) {
            System.out.println(exc);
            System.exit(1);
        }

        // metoda dropTable jest naszą własną metodą napisaną dla skrócenia programu
        // usuwa ona tabelę podaną jako argument
        // Aby w każdych okolicznościach stworzyć nową tabelę AUTOR
        // musimy usunąć ew.  już istniejącą tabelę AUTOR
        dropTable("POZYCJE"); // usunięcie tabeli pochodnej, będącej w relacji z tabelą AUTOR
        dropTable("AUTOR");   // usunięcie tabeli AUTOR

        String crestmt =    // from createdb.sql
                "create table AUTOR (\n" +
                "AUTID integer not null generated by default as identity,\n" +
                "NAME vachar(40) not null,\n" +
                "PRIMARY KEY(AUTID)\n" +
                ")";

        try {
            stmt.execute(crestmt);  // Executing statement with string

        } catch (SQLException exc) {                      // przechwycenie wyjątku:
            System.out.println("SQL except.: " + exc.getMessage());
            System.out.println("SQL state  : " + exc.getSQLState());
            System.out.println("Vendor errc: " + exc.getErrorCode());
            System.exit(1);
        } finally {
            try {
                stmt.close();
                con.close();
            } catch (SQLException exc) {
                System.out.println(exc);
                System.exit(1);
            }
        }
    }

    private void dropTable(String tname) throws SQLException {
        String query = String.format("DROP TABLE %s", tname);
        stmt.execute(query);
    }
}
